### ISSUE TITLE
Input monomer Molfile format has to be base64 encoded

### ISSUE THREAD

**Issue by TianhongZhang** [PistoiaHELM/HELM2NotationToolkit#3]
When adding a new monomer into Monomer Store via JSON format, the Molfile has to be base64 encoded, otherwise, an exception is thrown. Consider relaxing this requirement to accept original Molfile format.

**Comment by MarkusWeisser** [comment]
When adding a new monomer into the Monomer Store via JSON format, ths molfile can be in the base64 format. If this throws an exception the original molfile format will be used
