### ISSUE TITLE
All attachment points have to be fully defined for any new monomer

### ISSUE THREAD

**Issue by TianhongZhang** [PistoiaHELM/HELM2NotationToolkit#4]
When adding a new monomer into monomer store, if any of the  attachment is not fully defined, it will throw an exception. Consider ignoring non-defined attachments instead.

**Comment by MarkusWeisser** [comment]
Which attachment information is not fully defined? Does the smiles contain all needed information? What does not fully defined mean? Is there an example available?

**Comment by TianhongZhang** [comment]
In the input monomer json object, there are R1, R2, R3 keys, but the values are empty/null.

**Comment by MarkusWeisser** [comment]
If an attachment is not fully defined, it will not be added to the monomer -> so non-defined attachments will be ignored in the json monomer input
